// <auto-generated />
using System;
using CrudSimplesApiFiis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudSimplesApiFiis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220725212455_InitialCreation2")]
    partial class InitialCreation2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CategoriaFundoImobiliario", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundosImobiliariosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriasId", "FundosImobiliariosId");

                    b.HasIndex("FundosImobiliariosId");

                    b.ToTable("CategoriaFundoImobiliario");
                });

            modelBuilder.Entity("CrudSimplesApiFiis.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CrudSimplesApiFiis.Models.FundoImobiliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Administradora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ativo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("CotasEmitidas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataIpo")
                        .HasColumnType("DATE");

                    b.Property<string>("NomeFundo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicoAlvo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaAdministracao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPatrimonial")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FundosImobiliarios");
                });

            modelBuilder.Entity("CategoriaFundoImobiliario", b =>
                {
                    b.HasOne("CrudSimplesApiFiis.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrudSimplesApiFiis.Models.FundoImobiliario", null)
                        .WithMany()
                        .HasForeignKey("FundosImobiliariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
