// <auto-generated />
using System;
using CrudSimplesApiFiis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudSimplesApiFiis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220615193352_AddTabelaCategoria")]
    partial class AddTabelaCategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CrudSimplesApiFiis.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CrudSimplesApiFiis.Models.FundoImobiliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Administradora")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("CotasEmitidas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataIpo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFundo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Papel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicoAlvo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaAdministracao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPatrimonial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FundosImobiliarios");
                });
#pragma warning restore 612, 618
        }
    }
}
